import React, { Suspense } from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import theme from "./theme/theme";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import SidebarWrapper from "./component/SidebarWrapper/page";

// ** Contexts
import { AuthProvider } from "./contexts/AuthContext";

// ** auth hoock
import { useAuth } from "./hooks/useAuth";

// axios instance
import { AxiosInterceptor } from "./helper/axios";

// ** import file
import Loading from "./component/common/loading";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline enableColorScheme />
            <AuthProvider>
              <AxiosInterceptor>
                <SidebarWrapper>
                  <Suspense fallback={<Loading />}>{children}</Suspense>
                </SidebarWrapper>
              </AxiosInterceptor>
            </AuthProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
